### PR TITLE
fix(delete): Check if remote exists before deleting it

### LINKED ISSUE #82: Delete fails if remote doesn't exist
I have configured `deleteRemote = true` in my gitconfig for various branch types.
When working with multiple people on the same branch or when merging via web UI (we're using GitLab), I have to delete the local topic branch afterwards. A normal "git flow delete" fails because it tries to delete the remote, which doesn't exist.

Suggested fix: check if the remote branch exists before trying to delete it.

### PR DESCRIPTION
**Pull request by dermojo**
When deleting a remote branch, check whether if exists first. Trying to delete a branch that doesn't exist anymore isn't a failure.

The implemented fix is a simple check before trying to delete the remote branch.

Resolves #82

### CODE REVIEW

File: cmd/delete.go [hunk 1]
```diff
@@ -141,11 +141,20 @@ func performDelete(branchType, name, fullBranchName string, branchConfig config.
 			remoteName = "origin"
 		}
 
-		// Delete remote branch
-		if err := git.DeleteRemoteBranch(remoteName, fullBranchName); err != nil {
-			return &errors.GitError{Operation: fmt.Sprintf("delete remote branch '%s'", fullBranchName), Err: err}
+		deletedRemote := false
+		if git.RemoteBranchExists(remoteName, fullBranchName) {
```
Comment (alexrinass) [inline cmd/delete.go]: Nit: the `deletedRemote` boolean + separate conditional could be a single `if/else`:
```go
if git.RemoteBranchExists(remoteName, fullBranchName) {
    if err := git.DeleteRemoteBranch(remoteName, fullBranchName); err != nil {
        return &errors.GitError{Operation: fmt.Sprintf("delete remote branch '%s'", fullBranchName), Err: err}
    }
    fmt.Printf("Deleted branch %s and its remote tracking branch\n", fullBranchName)
} else {
    fmt.Printf("Deleted branch %s (no remote tracking branch found)\n", fullBranchName)
}
```
Not blocking — current version works fine.

**Review by alexrinass — APPROVED** [review]
Clean, focused fix that makes `delete --remote` resilient when the remote branch is already gone. The approach is consistent with the existing `RemoteBranchExists` guard in `cmd/finish.go:942`. The conditional output messaging is a nice touch — the user sees exactly what happened. Test updated correctly.

One known limitation: `RemoteBranchExists` checks local tracking refs, not the actual remote. If the branch was deleted via web UI without a local `git fetch --prune`, the stale ref causes a false positive and the subsequent `git push origin :branch` still fails. This is the same limitation in `cmd/finish.go:942` and is best addressed by #88 (fetch-before-delete). The hardcoded `"origin"` fallback at line 141 is tracked in #81.

🤖 Review generated with [Claude Code](https://claude.ai/claude-code)
